apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  replicas: {{ default 1 .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: node-cache-api
  template:
    metadata:
      labels:
        app: node-cache-api
    spec:
      containers:
        - image: "{{.Values.deploy.acrServer}}/hackfest/node-cache-api:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: node-cache-api
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: uri
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights                    
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always