apiVersion: v1
kind: Pod
metadata:
  name: iis-winsvrcore
spec:
  containers:
  - image: microsoft/iis:windowsservercore-ltsc2016
    imagePullPolicy: Always
    name: iis-winsvrcore
    resources:
      requests:
        memory: 1.5G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-akslab-aci-connector-windows-eastus
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule