# Default values for chart

service:
  type: LoadBalancer
  port: 3006

deploy:
  name: node-cache-api-deploy
  replicas: 3
  acrServer: "acrhackfestbrian13322.azurecr.io"
  imageTag: "v1"
  containerPort: 3006