apiVersion: v1
kind: Service
metadata:
  name: node-flights-api
  labels:
    name: node-flights-api
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: node-flights-api