apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  replicas: {{ default 1 .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: service-tracker-ui
  template:
    metadata:
      labels:
        app: service-tracker-ui
    spec:
      containers:
        - image: "{{.Values.deploy.acrServer}}/hackfest/service-tracker-ui:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: service-tracker-ui
          env:
            - name: FLIGHT_API
              value: http://flights-api:3003/latest
            - name: WEATHER_API
              value: http://weather-api:3015/styling
            - name: QUAKES_API
              value: http://quakes-api:3012/latest
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: 6dc23005-a1d0-418a-82bd-b232498b5221
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always