kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-go-rules
  labels:
    prometheus: kube-prometheus
    role: alert-rules
  namespace: monitoring
data:
  exampleapp.rules: |-
    groups:
    - name: samplegoapp.rules
      rules:
      - alert: ExampleSampleGoAppDeploymentLowReplicaCount
        expr: kube_deployment_status_replicas{deployment="sample-go"} < 3
        for: 30s
        labels:
          severity: "critical"
        annotations:
          description: "The Sample GO App is running with less than 3 replicas."
          summary: "App Not Fully Functional"