apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-default-namespace
  namespace: default
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: default
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          project: default