apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-dev-namespace-egress
  namespace: dev
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: dev
  egress:
  - {}
  policyTypes:
  - Egress