apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-default-namespace-egress
  namespace: default
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: default
  egress:
  - {}
  policyTypes:
  - Egress