apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-dev-namespace-ingress
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: service-tracker-ui
  ingress:
  - from: []
  egress:
  - {}
  policyTypes:
  - Egress