apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-dev-namespace
  namespace: dev
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: dev
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          project: dev